In [2]:
import tensorflow as tf

print("Version: ", tf.__version__)

Version:  2.7.0


In [3]:
# 创建两个常量
node1 = tf.constant([[3.0, 1.5], [2.5, 6.0]], tf.float32)
node2 = tf.constant([[4.0, 1.0], [5.0, 2.5]], tf.float32)
# 定义加法运算
node3 = tf.add(node1, node2)

# 输出 node3
node3

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[7. , 2.5],
       [7.5, 8.5]], dtype=float32)>

In [4]:
# 输出 node1
node1

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3. , 1.5],
       [2.5, 6. ]], dtype=float32)>

In [5]:
print(node3.numpy())

print(node3.shape)
print(node3.dtype)

[[7.  2.5]
 [7.5 8.5]]
(2, 2)
<dtype: 'float32'>


In [6]:
a = tf.constant([1, 2])
b = tf.constant([2.0, 3.0])

# 显示类型转换
a = tf.cast(a, tf.float32)

result = tf.add(a, b)

print(result)

tf.Tensor([3. 5.], shape=(2,), dtype=float32)
